apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: AuthService
      name: authentication
      auth_service: "ambassador-auth:80"
      path_prefix: "/extauth"
      allowed_headers: []
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
  selector:
    service: ambassador