apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ambassador
spec:
  rules:
  - host: incorehub2.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: ambassador
          servicePort: 80
